project_name: gitws

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gitws
    main: ./cmd/gitws
    binary: gitws
    env: [CGO_ENABLED=0]
    goos: [darwin, linux]
    goarch: [amd64, arm64]

archives:
  - id: default
    builds: [gitws]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: [README.md, LICENSE]

checksum:
  name_template: "checksums.txt"

brews:
  - name: gitws
    repository:
      owner: gitworkspaces
      name: homebrew-tap
    commit_author:
      name: "gitws-bot"
      email: "releases@gitws.dev"
    directory: Formula
    homepage: "https://gitws.dev"
    description: "Separate work/personal Git identities. Keys, SSH aliases, and guards."
    license: "MIT"
    test: |
      system "#{bin}/gitws", "--help"

release:
  github:
    owner: gitworkspaces
    name: gitws
  draft: false
  prerelease: false
